--- 
components: 
  schemas:
    BtsFreeMG_1000:
      description: 'Generic model of a multi channel BTS engineering sEMG sensor'
      properties:
        timeStamp:
          description: 'timestamp of the the current value'
          type: array
        feaisibility:
          description: 'Measures quality of the data point, '
          type: boolean
        data:
          description: 'list of EMG signal values corresponding to each channel'
          type: array
        index: 
          description: 'the sequential order or position of a data reading transmitted by the EMG sensor'
          type: integer
info: 
  description: "This represents the data model for BTS FreeMG 1000 data model to be used in INCODE project"
  title: 'BTS FreeMG1000'
  version: "1.0.0"
openapi: "3.0.0"

# These paths are merely representative.
paths: 
  /ngsi-ld/v1/entities: 
    get: 
      responses: 
        ? "200"
        : 
          description:  OK
          content: 
            application/ld+json: 
              schema: 
                type: object