--- 
components: 
  schemas:
    PolarH10AcclerometerPayload:
      description: 'Data model represents the Polar H10 sensor acclerometer data model'
      properties:
        clientId:
          description: 'Client ID'
          type: 'string'

        deviceId:
          description: 'Device ID'
          type: 'string'

        sessionId:
         description: 'Session ID'
         type: 'integer'

        sampleRate:
         description: 'Data acquisition rate'
         type: 'integer'

        timeStamp:
          description: 'Phone Timestamp'
          type: 'integer'

        sensorTimeStamp:
          description: 'Sensor Timestamp'
          type: 'integer'

        acc:
          description: 'Accelerometer data points - array of 36 arrays containing x, y, and z readings'
          type: 'array'
          items:
            type: 'array'
            items:
              type: 'integer'


info: 
  description: "This represents the data model of Polar H10 sensor acclerometer payload developed in context of INCODE-HEU project"
  title: 'Polar H10 Acclerometer Payload'
  version: "1.0.0"
openapi: "3.0.0"

# These paths are merely representative.
paths: 
  /ngsi-ld/v1/entities: 
    get: 
      responses: 
        ? "200"
        : 
          description:  OK
          content: 
            application/ld+json: 
              schema: 
                type: object