--- 
components: 
  schemas:
    PolarH10ECGPayload:
      description: 'Data model represents the Polar H10 sensor data model for ECG(EKG) topic payload'
      properties:
        clientId:
          description: 'Client ID'
          type: 'string'

        deviceId:
          description: 'Device ID'
          type: 'string'

        sessionId:
         description: 'Session ID'
         type: 'integer'

        sampleRate:
          type: 'integer'
          description: 'Data acquisition rate'

        timeStamp:
          type: 'integer'
          description: 'Phone Timestamp'

        sensorTimeStamp:
          type: 'integer'
          description: 'Sensor Timestamp'

        ecg:
          type: 'array'
          description: 'Electrocardiogram (ECG) data points'
          items:
            type: 'integer'

info: 
  description: "This represents the data model of Polar H10 payload for ECG topic developed in context of INCODE-HEU project"
  title: 'Polar H10 ECG topic payload'
  version: "1.0.0"
openapi: "3.0.0"

# These paths are merely representative.
paths: 
  /ngsi-ld/v1/entities: 
    get: 
      responses: 
        ? "200"
        : 
          description:  OK
          content: 
            application/ld+json: 
              schema: 
                type: object